application: wolfings-testing
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/img/WolfingsIcon29.png
  upload: static/img/WolfingsIcon29\.png

- url: /static/style
  static_dir: style/css

- url: /static/js
  static_dir: js/compiled

- url: /static/lib/closure
  static_dir: js/closure-library/closure

- url: /static
  static_dir: static

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
