SC=sass
SFLAGS=-t compressed --trace

# Directories
CSS=css
SCSS=scss

# Stylesheets to convert
DEPS=_utils
DEPS_LIST=${DEPS:%=$SCSS/%.scss}
STYLES=reset base frontpage
CSS_LIST=${STYLES:%=$CSS/%.css}


# Virtual Rules
all:V: $CSS_LIST
clean:V:
    rm -f $CSS/*.css


# Build rules
$CSS/%.css: $SCSS/%.scss $DEPS_LIST
    $SC $SFLAGS $SCSS/$stem.scss $target
