SC=sass
SFLAGS=-t compressed --trace

# Directories
CSS=css
SCSS=scss

# Stylesheets to convert
DEPS=_utils
DEPS_LIST=${DEPS:%=$SCSS/%.scss}
STYLES=reset base frontpage register coupon_snip business business_admin admin form
CSS_LIST=${STYLES:%=$CSS/%.css}


# Virtual Rules
all:V: $CSS_LIST
clean:V:
    rm -f $CSS/*.css


# Build rules
$CSS/%.css: $SCSS/%.scss $DEPS_LIST
    $SC $SFLAGS $SCSS/$stem.scss $target

$CSS/register.css: $SCSS/register.scss $SCSS/_utils.scss $SCSS/_buttons.scss
    $SC $SFLAGS $SCSS/register.scss $target

$CSS/coupon_snip.css: $SCSS/coupon_snip.scss $SCSS/_utils.scss $SCSS/_buttons.scss
    $SC $SFLAGS $SCSS/coupon_snip.scss $target
